CREATE TABLE CFOP_ESTADO
(
	ESTADOORIGEM VARCHAR(2),
	ESTADODESTINO VARCHAR(2),
	CFOP VARCHAR(10)
)
--DROP TABLE CFOP_ESTADO
INSERT INTO CFOP_ESTADO VALUES ('SP', 'RJ', '6.000')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'PE', '6.001')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'MG', '6.002')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'PB', '6.003')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'PR', '6.004')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'PI', '6.005')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'RO', '6.006')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'SE', '6.007')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'TO', '6.008')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'SE', '6.009')
INSERT INTO CFOP_ESTADO VALUES ('SP', 'PA', '6.010')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'RJ', '6.000')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'PE', '6.001')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'MG', '6.002')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'PB', '6.003')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'PR', '6.004')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'PI', '6.005')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'RO', '6.006')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'SE', '6.007')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'TO', '6.008')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'SE', '6.009')
INSERT INTO CFOP_ESTADO VALUES ('MG', 'PA', '6.010')